# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  PATH_PROJECT: ./src/W4G.Extensions/W4G.Extensions.csproj

steps:
- script: dotnet restore
  displayName: 'dotnet restore'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test --no-build --verbosity normal
  displayName: 'dotnet test'

- script: dotnet pack $(PATH_PROJECT) -c $(buildConfiguration) -o out
  displayName: 'dotnet pack'

- script: dotnet nuget push out/*.nupkg --api-key $(NUGET_API_KEY) --source $(NUGET_SERVER) --skip-duplicate
  displayName: 'nuget push'