# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PATH_PROJECT: ./src/W4G.Extensions/W4G.Extensions.csproj
      NUGET_SERVER:  ${{ secrets.NUGET_SERVER }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }} 
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build -c Release --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: Echo
      run: |
        echo "teste"
        echo 1 ${{ secrets.NUGET_SERVER }}
        echo 2 ${{ env.NUGET_SERVER }}
        echo 3 ${{ env.PATH_PROJECT }}
        echo 4 $PATH_PROJECT
    - name: Geração do package
      run: dotnet pack ${{ env.PATH_PROJECT }} -c Release -o out
    - name: Push no NuGet
      run: dotnet nuget push ./out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate
