name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PATH_PROJECT: ./src/W4G.Extensions/W4G.Extensions.csproj
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Definir configuração regional
      run: sudo localectl set-locale LANG=pt_BR.UTF-8
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build Debug
      run: dotnet build -c Debug --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal